# Generated by Django 4.1.5 on 2023-01-20 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('contact', models.IntegerField()),
                ('DOB', models.DateField()),
                ('password', models.CharField(max_length=500)),
            ],
        ),
    ]
